						<?php
//
// File generated by ... on the 2019-07-12T19:35:48+0200
// Please do not edit manually
//

/**
 * Classes and menus for jb-contactmethod (version 1.0.0)
 *
 * @author      iTop compiler
 * @license     http://opensource.org/licenses/AGPL-3.0
 */



class ContactMethod extends cmdbAbstractObject
{
	public static function Init()
	{
		$aParams = array(			'category' => 'bizmodel,searchable',
			'key_type' => 'autoincrement',
			'name_attcode' => array('person_id_friendlyname', 'contact_method', 'contact_detail'),
			'state_attcode' => '',
			'reconc_keys' => array('person_id', 'contact_method', 'contact_detail'),
			'db_table' => 'contactmethod',
			'db_key_field' => 'id',
			'db_finalclass_field' => '',
			'icon' => utils::GetAbsoluteUrlModulesRoot().'jb-contactmethod/images/person.png',
			'uniqueness_rules' => array (
  'unique_contact_method' => 
  array (
    'attributes' => 
    array (
      0 => 'person_id',
      1 => 'contact_method',
      2 => 'contact_detail',
    ),
    'filter' => NULL,
    'disabled' => NULL,
    'is_blocking' => NULL,
  ),
),);
		MetaModel::Init_Params($aParams);
		MetaModel::Init_InheritAttributes();
		MetaModel::Init_AddAttribute(new AttributeExternalKey("person_id", array("targetclass"=>'Person', "allowed_values"=>null, "sql"=>'person_id', "is_null_allowed"=>false, "on_target_delete"=>DEL_AUTO, "depends_on"=>array(), "display_style"=>'select', "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeEnum("contact_method", array("allowed_values"=>new ValueSetEnum("phone,mobile_phone,email"), "display_style"=>'list', "sql"=>'contact_method', "default_value"=>'', "is_null_allowed"=>false, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeString("contact_detail", array("allowed_values"=>null, "sql"=>'contact_detail', "default_value"=>'', "is_null_allowed"=>false, "depends_on"=>array(), "always_load_in_tables"=>false)));



		MetaModel::Init_SetZListItems('details', array (
  0 => 'person_id',
  1 => 'contact_method',
  2 => 'contact_detail',
));
		MetaModel::Init_SetZListItems('standard_search', array (
  0 => 'person_id',
  1 => 'contact_method',
  2 => 'contact_detail',
));
		MetaModel::Init_SetZListItems('list', array (
  0 => 'person_id',
  1 => 'contact_method',
  2 => 'contact_detail',
));
;
	}


}