<?php
/**
 * @copyright   Copyright (C) 2019-2020 Jeffrey Bostoen
 * @license     https://www.gnu.org/licenses/gpl-3.0.en.html
 * @version     2020-04-09 17:01:06
 *
 * Localized data
 */

Dict::Add('EN US', 'English', 'English', array(

	//	'Class:SomeClass' => 'Class name',
	//	'Class:SomeClass+' => 'More info on class name',
	//	'Class:SomeClass/Attribute:some_attribute' => 'your translation for the label',
    //	'Class:SomeClass/Attribute:some_attribute/Value:some_value' => 'your translation for a value',
    //	'Class:SomeClass/Attribute:some_attribute/Value:some_value+' => 'your translation for more info on the value',
	
	'Class:izSoftware' => 'izSoftware',
	'Class:izSoftware+' => 'Generic name for the software',
	'Class:izSoftware/Attribute:name' => 'Name of the software',
	'Class:izSoftware/Attribute:name+' => 'Main name of the software, such as MS Office, MS Windows Server. Does not include version info or a year.',
	'Class:izSoftware/Attribute:org_id' => 'Organization',
	'Class:izSoftware/Attribute:org_id+' => 'Organization where this software is used',
	'Class:izSoftware/Attribute:vendor' => 'Vendor',
	'Class:izSoftware/Attribute:vendor+' => 'Vendor',
	'Class:izSoftware/Attribute:type' => 'Type',
	'Class:izSoftware/Attribute:type+' => 'Type of software',
	'Class:izSoftware/Attribute:type/Value:client_software' => 'Client software',
	'Class:izSoftware/Attribute:type/Value:cloud_software' => 'Cloud software',
	'Class:izSoftware/Attribute:type/Value:operating_system' => 'Operating system',
	'Class:izSoftware/Attribute:type/Value:server_software' => 'Server software',
	'Class:izSoftware/Attribute:versions_list' => 'Versions',
	'Class:izSoftware/Attribute:versions_list+' => 'Versions',
	
	'Class:izSoftwareVersion' => 'izSoftwareVersion',
	'Class:izSoftwareVersion+' => 'Software version',
	'Class:izSoftwareVersion/Attribute:org_id' => 'Organization',
	'Class:izSoftwareVersion/Attribute:org_id+' => 'Organization where this software is used',
	'Class:izSoftwareVersion/Attribute:software_id' => 'Software',
	'Class:izSoftwareVersion/Attribute:software_id+' => 'Software name',
	'Class:izSoftwareVersion/Attribute:version' => 'Version',
	'Class:izSoftwareVersion/Attribute:version+' => 'Version of this software. Could be a name, build number, ...',
	'Class:izSoftwareVersion/Attribute:installations_list' => 'Installations',
	'Class:izSoftwareVersion/Attribute:installations_list+' => 'Installations of this software version on physical or virtual devices',
	
	'Class:izSoftwareInstallation' => 'izSoftwareInstallation',
	'Class:izSoftwareInstallation+' => 'Software installation on a physical or virtual device.',
	'Class:izSoftwareInstallation/Name' => '%1$s | %2$s',
	'Class:izSoftwareInstallation/Attribute:org_id' => 'Organization',
	'Class:izSoftwareInstallation/Attribute:org_id+' => 'Organization',
	'Class:izSoftwareInstallation/Attribute:softwareversion_id' => 'Software version',
	'Class:izSoftwareInstallation/Attribute:softwareversion_id+' => 'Software version which is installed on the device',
	'Class:izSoftwareInstallation/Attribute:license_id' => 'License',
	'Class:izSoftwareInstallation/Attribute:license_id+' => 'License info',
	'Class:izSoftwareInstallation/Attribute:functionalci_id' => 'Host',
	'Class:izSoftwareInstallation/Attribute:functionalci_id+' => 'Device on which the software is installed',
	'Class:izSoftwareInstallation/Attribute:version_details' => 'Version detail',
	'Class:izSoftwareInstallation/Attribute:version_details+' => 'Detailed version info',
	
	'Class:izLicense' => 'izLicense',
	'Class:izLicense+' => 'License',
	'Class:izLicense/Attribute:name' => 'Name',
	'Class:izLicense/Attribute:name+' => 'Short name of this license',
	'Class:izLicense/Attribute:org_id' => 'Organization',
	'Class:izLicense/Attribute:org_id+' => 'Organization to which this license belongs',
	'Class:izLicense/Attribute:provider_org_id' => 'Provider',
	'Class:izLicense/Attribute:provider_org_id+' => 'Organization providing this license',
	'Class:izLicense/Attribute:softwareversion_id' => 'Software version',
	'Class:izLicense/Attribute:softwareversion_id+' => 'Software version',
	'Class:izLicense/Attribute:comment' => 'Comment',
	'Class:izLicense/Attribute:comment+' => 'Comment about this license. Could be use cases, special notes, requirements such as a license USB key, ...',
	'Class:izLicense/Attribute:start_date' => 'Start date',
	'Class:izLicense/Attribute:start_date+' => 'Start date',
	'Class:izLicense/Attribute:end_date' => 'End date',
	'Class:izLicense/Attribute:end_date+' => 'End date',
	'Class:izLicense/Attribute:reminder_date' => 'Reminder date',
	'Class:izLicense/Attribute:reminder_date+' => 'Reminder date',
	'Class:izLicense/Attribute:type' => 'Type',
	'Class:izLicense/Attribute:type+' => 'License type. Who/what is licensed?',
	'Class:izLicense/Attribute:type/Value:single_user' => 'Single user',
	'Class:izLicense/Attribute:type/Value:concurrent_user' => 'Concurrent user',
	'Class:izLicense/Attribute:type/Value:organization' => 'Organization',
	'Class:izLicense/Attribute:type/Value:device' => 'Device',
	'Class:izLicense/Attribute:purchase_type' => 'Purchase type',
	'Class:izLicense/Attribute:purchase_type+' => 'Chosen purchase formula',
	'Class:izLicense/Attribute:purchase_type/Value:one_time' => 'One time',
	'Class:izLicense/Attribute:purchase_type/Value:limited' => 'Limited subscription',
	'Class:izLicense/Attribute:purchase_type/Value:autorenewal' => 'Automatically renewed',
	'Class:izLicense/Attribute:amount' => 'Amount',
	'Class:izLicense/Attribute:amount+' => 'Amount of users, devices, organizations',
	'Class:izLicense/Attribute:serial' => 'Serial key',
	'Class:izLicense/Attribute:serial+' => 'Serial key',
	'Class:izLicense/Attribute:contacts_list' => 'Licensed users',
	'Class:izLicense/Attribute:contacts_list+' => 'Persons or Teams who use this license',
	'Class:izLicense/Attribute:documents_list' => 'Documents',
	'Class:izLicense/Attribute:documents_list+' => 'Documents related to this license',
	'Class:izLicense/Attribute:installations_list' => 'Licensed devices',
	'Class:izLicense/Attribute:installations_list+' => 'Devices using this license',
		
	'Class:lnkIzLicenseToContact' => 'Link izLicense / Contact',
	'Class:lnkIzLicenseToContact+' => 'Link between izLicense and Contact',
	'Class:lnkIzLicenseToContact/Name' => '%1$s | %2$s',
	'Class:lnkIzLicenseToContact/Attribute:izlicense_id' => 'License',
	'Class:lnkIzLicenseToContact/Attribute:izlicense_id+' => 'License',
	'Class:lnkIzLicenseToContact/Attribute:contact_id' => 'Contact',
	'Class:lnkIzLicenseToContact/Attribute:contact_id+' => 'Contact. Likely a Person, but could also be a Team.',
	'Class:lnkIzLicenseToContact/Attribute:comment' => 'Comment',
	'Class:lnkIzLicenseToContact/Attribute:comment+' => 'Comment. Reason of installation, downgrade rights, ... could be logged here.',
	
	'Class:lnkIzLicenseToDocument' => 'Link izLicense / Document',
	'Class:lnkIzLicenseToDocument+' => 'Link between izLicense and Document',
	'Class:lnkIzLicenseToDocument/Name' => '%1$s | %2$s',
	'Class:lnkIzLicenseToDocument/Attribute:izlicense_id' => 'License',
	'Class:lnkIzLicenseToDocument/Attribute:izlicense_id+' => 'License',
	'Class:lnkIzLicenseToDocument/Attribute:document_id' => 'Document',
	'Class:lnkIzLicenseToDocument/Attribute:document_id+' => 'Document related to this license.',
	'Class:lnkIzLicenseToDocument/Attribute:comment' => 'Comment',
	'Class:lnkIzLicenseToDocument/Attribute:comment+' => 'Comment. Extra info can be added here.',
	
));

